services:
  bitcoin-regtest:
    image: ruimarinho/bitcoin-core:latest
    command:
      -regtest=1
      -server=1
      -txindex=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=user
      -rpcpassword=password
    ports:
      - "18443:18443"
    networks:
      - corsa
    volumes:
      - bitcoin-data:/data
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=user", "-rpcpassword=password", "getblockchaininfo"]
      interval: 5s
      timeout: 5s
      retries: 5

  corsa-reth:
    build:
      context: ./corsa-reth
      dockerfile: Dockerfile
    environment:
      - BTC_NETWORK=regtest
      - BTC_RPC_URL=http://bitcoin-regtest
      - BTC_RPC_USER=user
      - BTC_RPC_PASSWORD=password
      - NETWORK_SIGNING_URL=http://corsa-enclave:5555
      - NETWORK_UTXO_URL=http://hyperstate-utxos:5557
      - BTX_TX_QUEUE_URL=http://bitcoin-tx-queue:5558
    ports:
      - "8545:8545"
    networks:
      - corsa
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-H", "Content-Type: application/json", "--data", '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}', "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 5

  bitcoin-tx-queue:
    build:
      context: ./bitcoin-tx-queue
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
    ports:
      - "5558:5558"
    command: [
      "bitcoin-tx-queue",
      "--host", "0.0.0.0",
      "--port", "5558",
      "--bitcoin-url", "http://bitcoin-regtest",
      "--network", "regtest",
      "--rpc-username", "user",
      "--rpc-password", "password"
    ]
    networks:
      - corsa
    depends_on:
      bitcoin-regtest:
        condition: service_healthy

  corsa-enclave:
    build:
      context: ./corsa-enclave
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
    ports:
      - "5555:5555"
    command: >
      corsa-enclave
      --host 0.0.0.0
      --port 5555
      --seed 000102030405060708090a0b0c0d0e0f
    networks:
      - corsa
    depends_on:
      corsa-reth:
        condition: service_started

  hyperstate-utxos:
    build:
      context: ./hyperstate-utxos
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
    ports:
      - "5557:5557"
    command: >
      hyperstate-utxos
      --host 0.0.0.0
      --port 5557
      --log-level info
    networks:
      - corsa
    volumes:
      - utxo-data:/data
    depends_on:
      corsa-reth:
        condition: service_started

  hyperstate-indexer:
    build:
      context: ./hyperstate-indexer
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
    networks:
      - corsa
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
      hyperstate-utxos:
        condition: service_started
    command: [
      "hyperstate-indexer",
      "--webhook-url", "http://hyperstate-utxos:5557/hook",
      "--rpc-host", "bitcoin-regtest",
      "--rpc-port", "18443",
      "--rpc-user", "user",
      "--rpc-password", "password",
      "--start-height", "0"
    ]

  faucet:
    build:
      context: ./faucet
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
      - FAUCET_PRIVATE_KEY=${FAUCET_PRIVATE_KEY}
    ports:
      - "5556:5556"
    networks:
      - corsa
    depends_on:
      corsa-reth:
        condition: service_healthy
    command: [
      "--rpc-url", "http://corsa-reth:8545",
      "--private-key", "${FAUCET_PRIVATE_KEY}",
      "--host", "0.0.0.0"
    ]

networks:
  corsa:
    driver: bridge

volumes:
  bitcoin-data:
  logs:
  utxo-data: