services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - "18444:18444"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sova_network
    depends_on:
      - bitcoin-regtest
  
  bitcoin-regtest:
    image: ruimarinho/bitcoin-core@sha256:79dd32455cf8c268c63e5d0114cc9882a8857e942b1d17a6b8ec40a6d44e3981
    command:
      -regtest=1
      -server=1
      -txindex=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=user
      -rpcpassword=password
    ports:
      - "18443:18443"
    networks:
      - sova_network
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
    healthcheck:
      test: [
        "CMD",
        "bitcoin-cli",
        "-regtest",
        "-rpcuser=user",
        "-rpcpassword=password",
        "getblockchaininfo"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  sova-reth:
    build:
      context: ./sova-reth
      dockerfile: Dockerfile
    environment:
      - BTC_NETWORK=regtest
      - BTC_RPC_URL=http://bitcoin-regtest
      - BTC_RPC_USER=user
      - BTC_RPC_PASSWORD=password
      - NETWORK_SIGNING_URL=http://hyperstate-enclave:5555
      - NETWORK_UTXO_URL=http://hyperstate-utxos:5557
      - BTC_TX_QUEUE_URL=http://bitcoin-tx-queue:5558
    ports:
      - "8545:8545"
    networks:
      - sova_network
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
    healthcheck:
      test: [
        "CMD",
        "curl",
        "-H", "Content-Type: application/json",
        "--data", '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}',
        "http://localhost:8545"
      ]
      interval: 5s
      timeout: 10s
      retries: 5

  bitcoin-tx-queue:
    build:
      context: ./bitcoin-tx-queue
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
    ports:
      - "5558:5558"
    command: [
      "bitcoin-tx-queue",
      "--host", "0.0.0.0",
      "--port", "5558",
      "--bitcoin-url", "http://bitcoin-regtest",
      "--network", "regtest",
      "--rpc-username", "user",
      "--rpc-password", "password"
    ]
    networks:
      - sova_network
    depends_on:
      bitcoin-regtest:
        condition: service_healthy

  hyperstate-enclave:
    build:
      context: ./hyperstate-enclave
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
      - ENCLAVE_SEED=${ENCLAVE_SEED}
    ports:
      - "5555:5555"
    command: >
      hyperstate-enclave
      --host 0.0.0.0
      --port 5555
      --seed ${ENCLAVE_SEED}
    networks:
      - sova_network

  hyperstate-utxos:
    build:
      context: ./hyperstate-utxos
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
    ports:
      - "5557:5557"
    command: >
      hyperstate-utxos
      --host 0.0.0.0
      --port 5557
      --log-level info
      --datasource sqlite
    networks:
      - sova_network
    volumes:
      - utxo-data:/data

  hyperstate-indexer:
    build:
      context: ./hyperstate-indexer
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
      - INDEXER_START_BLOCK=${INDEXER_START_BLOCK}
    networks:
      - sova_network
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
      hyperstate-utxos:
        condition: service_started
    command: [
      "hyperstate-indexer",
      "--webhook-url", "http://hyperstate-utxos:5557/hook",
      "--rpc-host", "bitcoin-regtest",
      "--rpc-port", "18443",
      "--rpc-user", "user",
      "--rpc-password", "password",
      "--start-height", "${INDEXER_START_BLOCK}"
    ]

  hyperstate-testnet-faucet:
    build:
      context: ./hyperstate-testnet-faucet
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
      - FAUCET_PRIVATE_KEY=${FAUCET_PRIVATE_KEY}
    ports:
      - "5556:5556"
    networks:
      - sova_network
    depends_on:
      sova-reth:
        condition: service_healthy
    command: [
      "--rpc-url", "http://sova-reth:8545",
      "--private-key", "${FAUCET_PRIVATE_KEY}",
      "--host", "0.0.0.0"
    ]

networks:
  sova_network:
    driver: bridge

volumes:
  bitcoin-data:
  logs:
  utxo-data:
