include:
  - ./corsascan/docker-compose/geth.yml

services:
  satoshi-suite:
    build:
      context: ./satoshi-suite
      dockerfile: ../Dockerfile.satoshi-suite
    volumes:
      - ./logs:/app/logs
      - bitcoin-data:/root/.bitcoin
    networks:
      - corsa
    ports:
      - "5555:5555"
    command: >
      sh -c "just start-bitcoind > /app/logs/bitcoind.log &&
             just mine-blocks user-1 101 &&
             tail -f /app/logs/bitcoind.log"

  corsa-reth:
    build:
      context: ./corsa-reth
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
    networks:
      - corsa
    depends_on:
      - satoshi-suite
    command: >
      sh -c "just run-chain > /app/logs/corsa-reth.log &&
             tail -f /app/logs/corsa-reth.log"

  faucet:
    build:
      context: ./faucet
      dockerfile: Dockerfile
    ports:
      - "5556:5556"
    networks:
      - corsa
    depends_on:
      - corsa-reth
    command: >
      sh -c "corsa-testnet-faucet
             --rpc-url http://corsa-reth:8545
             --private-key YOUR_PRIVATE_KEY_HERE
             --tokens-per-request 10000000000000000000
             --port 5556
             --host 0.0.0.0
             --gas-price-gwei 1
             --gas-limit 21000"

networks:
  corsa:
    driver: bridge

volumes:
  bitcoin-data: