# This docker-compose file is used to run a Sova OP devnet sequencer.
#
# There is one profiles in this file: `core`.
# The `core` profile is used to run the core Sova components without the OP stack.
# Consensus is mocked by the --dev and --chain flags in the sova-reth node.

#! In a production environment, this should not be used. It is intended to be used
#! for testing and development purposes only.
services:
  # Core Sova components
  sova-reth:
    image: ghcr.io/sovanetwork/sova-reth:latest
    environment:
      NETWORK_UTXOS_API_KEY: ${INDEXER_SHARED_API_KEY:-}
      SOVA_DERIVATION_XPUB: ${SOVA_DERIVATION_XPUB:-}
      SOVA_SEQUENCER_MODE: true
    command: >
      node
      --chain dev
      --btc-network ${NETWORK:-regtest}
      --btc-network-url http://bitcoin-regtest
      --btc-rpc-username user
      --btc-rpc-password password
      --network-utxos-url http://network-indexer:3031
      --sentinel-url http://sentinel-server:50051
      --sentinel-confirmation-threshold 6
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --http.api all
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --datadir /var/lib/sova
      --log.stdout.filter ${RUST_LOG:-info}
      --dev
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
    networks:
      - sova_network
    volumes:
      - sequencer-data:/var/lib/sova
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
      sentinel-server:
        condition: service_started
    profiles: [core]
    healthcheck:
      test: [
        "CMD",
        "curl",
        "-H", "Content-Type: application/json",
        "--data", '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}',
        "http://localhost:8545"
      ]
      interval: 5s
      timeout: 10s
      retries: 5

  sentinel-server:
    image: ghcr.io/sovanetwork/sova-sentinel:v0.1.2
    environment:
      - SOVA_SENTINEL_HOST=0.0.0.0
      - SOVA_SENTINEL_PORT=50051
      - SOVA_SENTINEL_DB_PATH=/app/data/slot_locks.db
      - BITCOIN_RPC_URL=http://bitcoin-regtest:18443
      - BITCOIN_RPC_USER=user
      - BITCOIN_RPC_PASS=password
      - BITCOIN_CONFIRMATION_THRESHOLD=6
      - BITCOIN_REVERT_THRESHOLD=18
      - BITCOIN_RPC_MAX_RETRIES=5
      - RUST_LOG=${RUST_LOG:-info}
    ports:
      - "50051:50051"
    networks:
      - sova_network
    volumes:
      - sentinel-data:/app/data
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
    profiles: [core]
  
  # Supporting Sova components
  bitcoin-regtest:
    image: ruimarinho/bitcoin-core@sha256:79dd32455cf8c268c63e5d0114cc9882a8857e942b1d17a6b8ec40a6d44e3981 # ruimarinho/bitcoin-core:24
    command:
      -regtest=1
      -server=1
      -txindex=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=user
      -rpcpassword=password
    ports:
      - "18443:18443"
    networks:
      - sova_network
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
    healthcheck:
      test: [
        "CMD",
        "bitcoin-cli",
        "-regtest",
        "-rpcuser=user",
        "-rpcpassword=password",
        "getblockchaininfo"
      ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  network-enclave:
    image: ghcr.io/sovanetwork/network-enclave:v0.0.6
    environment:
      - LOG_LEVEL=${RUST_LOG:-info}
      - BIP32_SEED=${BIP32_SEED}
      - ENCLAVE_API_KEY=${ENCLAVE_SHARED_API_KEY:-}
    ports:
      - "5555:5555"
    command: >
      --host 0.0.0.0
      --port 5555
      --network ${NETWORK:-regtest}
    networks:
      - sova_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  network-indexer:
    image: ghcr.io/sovanetwork/network-indexer:v0.1.2
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - NETWORK=${NETWORK:-regtest}
      - RPC_HOST=bitcoin-regtest
      - RPC_PORT=${RPC_PORT:-18443}
      - RPC_USER=${RPC_USER:-user}
      - RPC_PASSWORD=${RPC_PASSWORD:-password}
      - SOCKET_PATH=${SOCKET_PATH:-/tmp/network-utxos.sock}
      - START_HEIGHT=${INDEXER_START_BLOCK:-0}
      - POLLING_RATE=${INDEXER_POLLING_RATE:-500}
      - MAX_BLOCKS_PER_BATCH=${INDEXER_MAX_BLOCKS:-200}
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-3031}
      - ENCLAVE_URL=http://network-enclave:5555
      - UTXO_URL=http://network-utxos:5557
      - ENCLAVE_API_KEY=${ENCLAVE_SHARED_API_KEY:-}
      - INDEXER_API_KEY=${INDEXER_SHARED_API_KEY:-}
    ports:
      - "3031:3031"
    networks:
      - sova_network
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
      network-utxos:
        condition: service_started
    volumes:
      - socket:/tmp

  network-utxos:
    image: ghcr.io/sovanetwork/network-utxos:v0.1.2
    environment:
      - RUST_LOG=${RUST_LOG:-info}
      - HOST=${UTXO_HOST:-0.0.0.0}
      - PORT=${UTXO_PORT:-5557}
      - LOG_LEVEL=${UTXO_LOG_LEVEL:-info}
      - DATASOURCE=${UTXO_DATASOURCE:-sqlite}
      - SOCKET_PATH=${SOCKET_PATH:-/tmp/network-utxos.sock}
    ports:
      - "5557:5557"
    networks:
      - sova_network
    volumes:
      - utxo-data:/data
      - socket:/tmp

networks:
  sova_network:
    driver: bridge

volumes:
  bitcoin-data:
  sequencer-data:
  sentinel-data:
  utxo-data:
  socket:
