services:
  # Core Sova components
  # TODO(powvt): Update --rollup.sequencer-http to the actual Sova sequencer url
  # NOTE(powvt): Other validator flags: https://reth.rs/run/optimism.html?highlight=sequencer#running-op-reth
  sova-reth:
    image: ghcr.io/sovanetwork/sova-reth:v0.0.6
    command: >
      node
      --chain /config/testnet-sepolia/genesis.json
      --btc-network ${NETWORK:-regtest}
      --btc-network-url http://${SEQUENCER_IP}
      --btc-rpc-username user
      --btc-rpc-password password
      --network-utxos-url http://${SEQUENCER_IP}:3031 
      --sentinel-url http://${SENTINEL_IP}:50051
      --sentinel-confirmation-threshold 6
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --http.api all
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret=/config/testnet-sepolia/jwt.txt
      --port=30303
      --rollup.sequencer-http=http://${SEQUENCER_IP}:8545
      --rollup.disable-tx-pool-gossip
      --bootnodes=enode://188eaf661774caf05238375debdb5c96bfa2a23d9b99e3843995bb4e46901fa09e13447d8c1c56e0ac1a93e335b85be07b444f4c8ffe24f024002399f7895559@${SEQUENCER_IP}:30303
      --metrics=0.0.0.0:6060
      --datadir /var/lib/sova
      --log.stdout.filter ${RUST_LOG:-info}
    ports:
      - "8545:8545"     # HTTP RPC
      - "8546:8546"     # WebSocket RPC
      - "30303:30303"   # P2P TCP
      - "30303:30303/udp"  # P2P UDP
      - "6060:6060"     # Metrics
    networks:
      - sova_network
    volumes:
      - validator-data:/var/lib/sova
      - ../config:/config
      #healthcheck:
      #  test: [
      #    "CMD",
      #    "curl",
      #    "-H", "Content-Type: application/json",
      #    "--data", '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}',
      #    "http://sova-reth:8545"
      #  ]
      #  interval: 5s
      #  timeout: 10s
      #  retries: 5

  # OP Stack components
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.13.4
    command: >
      op-node
      --l2=http://sova-reth:8551
      --l2.enginekind=reth
      --l2.jwt-secret=/config/testnet-sepolia/jwt.txt
      --interop.jwt-secret=/config/testnet-sepolia/jwt.txt
      --verifier.l1-confs=4
      --rollup.config=/config/testnet-sepolia/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=9545
      --rpc.enable-admin
      --l1=${ALCHEMY_L1_RPC_URL}
      --l1.rpckind=alchemy
      --l1.beacon=${L1_BEACON_URL}
      --p2p.listen.ip=0.0.0.0
      --p2p.listen.tcp=9222
      --p2p.listen.udp=9222
      --p2p.scoring=light
      --p2p.bootnodes=enr:-JG4QGg0gEy8ooIvbHAqKslHoHgiA4Iz_1MgRGuWlztbgOKhckDHMMBwnO8CGEiGZ9CtpB4XVGNpB2eRJ2PwBAqTteeGAZeqpH_OgmlkgnY0gmlwhAoAAQmJc2VjcDI1NmsxoQM64-mzcJiRGB7iZ2zft1uCmVuhg9KkxkDCJc6ZFWzp34N0Y3CCJAaDdWRwgiQG
      --metrics.enabled
      --metrics.addr=0.0.0.0
      --metrics.port=7300
      --log.level=info
    volumes:
      - ../config:/config
    ports:
      - "9545:9545"     # RPC
      - "9222:9222"     # P2P TCP
      - "9223:9222/udp" # P2P UDP
      - "7300:7300"     # Metrics
    depends_on:
      - sova-reth
    networks:
      - sova_network

networks:
  sova_network:
    driver: bridge

volumes:
  validator-data:
  sentinel-data:
  socket:
