services:
  # Core Sova components
  # TODO(powvt): Update --rollup.sequencer-http to the actual Sova sequencer url
  # NOTE(powvt): Other validator flags: https://reth.rs/run/optimism.html?highlight=sequencer#running-op-reth
  sova-reth:
    image: ghcr.io/sovanetwork/sova-reth:v0.0.6
    command: >
      node
      --chain /config/testnet-sepolia/genesis.json
      --btc-network ${NETWORK:-regtest}
      --btc-network-url http://bitcoin-regtest
      --btc-rpc-username user
      --btc-rpc-password password
      --network-utxos-url http://network-indexer:3031 
      --sentinel-url http://sentinel-server:50051
      --sentinel-confirmation-threshold 6
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --http.api all
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret=/config/testnet-sepolia/jwt.txt
      --discovery.port=30303
      --nat=extip:0.0.0.0
      --rollup.sequencer-http http://YOUR_SEQUENCER_PUBLIC_IP:8545
      --rollup.disable-tx-pool-gossip
      --rollup.discovery.v4
      --bootnodes=${SEQUENCER_BOOTNODE}
      --metrics=0.0.0.0:6060
      --datadir /var/lib/sova
      --log.stdout.filter ${RUST_LOG:-info}
    ports:
      - "8547:8545"     # HTTP RPC
      - "8548:8546"     # WebSocket RPC
      - "8552:8551"     # Engine API
      - "30304:30303"   # P2P TCP (different port)
      - "30304:30303/udp"  # P2P UDP
      - "6061:6060"     # Metrics (different port)
    networks:
      - sova_network
    volumes:
      - sequencer-data:/var/lib/sova
      - ../config:/config
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
      sentinel-server:
        condition: service_started
    profiles: [core]
    healthcheck:
      test: [
        "CMD",
        "curl",
        "-H", "Content-Type: application/json",
        "--data", '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}',
        "http://localhost:8545"
      ]
      interval: 5s
      timeout: 10s
      retries: 5

  sentinel-server:
    image: ghcr.io/sovanetwork/sova-sentinel:v0.1.2
    environment:
      - SOVA_SENTINEL_HOST=0.0.0.0
      - SOVA_SENTINEL_PORT=50051
      - SOVA_SENTINEL_DB_PATH=/app/data/slot_locks.db
      - BITCOIN_RPC_URL=http://bitcoin-regtest:18443
      - BITCOIN_RPC_USER=user
      - BITCOIN_RPC_PASS=password
      - BITCOIN_CONFIRMATION_THRESHOLD=6
      - BITCOIN_REVERT_THRESHOLD=18
      - BITCOIN_RPC_MAX_RETRIES=5
      - RUST_LOG=${RUST_LOG:-info}
    ports:
      - "50051:50051"
    networks:
      - sova_network
    volumes:
      - sentinel-data:/app/data
    depends_on:
      bitcoin-regtest:
        condition: service_healthy
    profiles: [core]
  
  # Supporting Sova components
  bitcoin-regtest:
    image: ruimarinho/bitcoin-core@sha256:79dd32455cf8c268c63e5d0114cc9882a8857e942b1d17a6b8ec40a6d44e3981 # ruimarinho/bitcoin-core:24
    command:
      -regtest=1
      -server=1
      -txindex=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=user
      -rpcpassword=password
    ports:
      - "18443:18443"
    networks:
      - sova_network
    volumes:
      - bitcoin-data:/home/bitcoin/.bitcoin
    healthcheck:
      test: [
        "CMD",
        "bitcoin-cli",
        "-regtest",
        "-rpcuser=user",
        "-rpcpassword=password",
        "getblockchaininfo"
      ]
      interval: 5s
      timeout: 5s
      retries: 5

  # OP Stack components
  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.13.4
    command: >
      op-node
      --l2=http://sova-reth:8551
      --l2.enginekind=reth
      --l2.jwt-secret=/config/testnet-sepolia/jwt.txt
      --interop.jwt-secret=/config/testnet-sepolia/jwt.txt
      --verifier.l1-confs=4
      --rollup.config=/config/testnet-sepolia/rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=9545
      --rpc.enable-admin
      --l1=${ALCHEMY_L1_RPC_URL}
      --l1.rpckind=alchemy
      --l1.beacon=${L1_BEACON_URL}
      --p2p.listen.ip=0.0.0.0
      --p2p.listen.tcp=9003
      --p2p.listen.udp=9003
      --p2p.bootnodes=${SEQUENCER_P2P_BOOTNODE}
      --p2p.scoring=none
      --p2p.ban.peers=true
      --syncmode=consensus-layer
    volumes:
      - ../config:/config
    ports:
      - "9546:9545"     # Rollup RPC (different port)
      - "9004:9003"     # P2P TCP (different port)
      - "9004:9003/udp" # P2P UDP
      - "7303:7300"     # Metrics (different port)
    networks:
      - sova_network
    profiles: [op-stack]

networks:
  sova_network:
    driver: bridge

volumes:
  bitcoin-data:
  sequencer-data:
  sentinel-data:
  utxo-data:
  socket:
